//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Octopus.rc
//
#define TIMER_TEMP                      10
#define TIMER_LAMBDA                    11
#define TIMER_SCRIPT                    12
#define TIMER_SCAN                      13
#define TIMER_STAGE                     14
#define TIMER_PIEZO                     15
#define TIMER_POL_POS                   16
#define TIMER_POL_SCAN                  17
#define TIMER_ADC                       18
#define TIMER_GRAT                      19
#define TIMER_TRIG                      20
#define TIMER_FOCUS                     21
#define TIMER_ROI                       22
#define TIMER_GEN_FOCUS                 23
#define TIMER_ROI_FOCUS                 24
#define IDC_BACKGROUND                  101
#define IDM_BOARD                       101
#define IDM_INPUT                       102
#define IDM_OUTPUT                      103
#define IDM_ACQ                         104
#define IDM_CGL                         105
#define IDC_FOCUS                       109
#define IDM_START                       110
#define IDI_ICON1                       111
#define IDM_STOP                        111
#define IDB_RUNNING                     115
#define IDD_DIALOG1                     115
#define AFX_CAMERACOOLING               115
#define IDB_STOPPED                     116
#define IDM_SV                          120
#define IDM_ANA_IO                      121
#define IDM_DIG_IO                      122
#define IDR_MAINFRAME                   127
#define IDR_OctopusTYPE                 128
#define IDM_CT                          130
#define IDS_OBJECT_PROPERTIES           131
#define IDS_APP_TITLE                   132
#define IDD_ABOUTBOX                    133
#define IDM_VIEW                        140
#define IDB_NO                          144
#define IDB_YES                         145
#define IDM_ABOUT                       150
#define IDM_USEWINMSGS                  160
#define IDM_USECALLBACKS                170
#define IDM_FLUSHINPROCESS              180
#define BOARDBOX                        200
#define IDD_BOARD                       201
#define ABOUTBOX                        203
#define IDD_APIVERSION                  250
#define IDD_DRVVERSION                  251
#define ACQBOX                          300
#define IDD_DISABLEIN                   301
#define IDD_DISPLAY                     302
#define IDD_FILEWRITE                   303
#define IDD_BURST                       304
#define IDD_CONTINUOUS                  305
#define IDD_INFREQ                      306
#define IDD_NUMBUF                      307
#define IDD_BUFSIZE                     308
#define IDD_INDMA                       309
#define IDD_PEAK                        310
#define IDD_WAVEFREQ                    311
#define IDD_OUTFREQ                     312
#define IDD_DISABLEOUT                  313
#define IDD_OUTDMA                      314
#define IDD_SINE                        316
#define IDD_SQUARE                      317
#define IDD_TRIANGLE                    318
#define LABEL_IN1                       350
#define LABEL_IN2                       351
#define LABEL_IN3                       352
#define LABEL_IN4                       353
#define LABEL_IN5                       354
#define LABEL_IN6                       355
#define LABEL_OUT1                      360
#define LABEL_OUT2                      361
#define LABEL_OUT3                      362
#define LABEL_OUT4                      363
#define LABEL_IO1                       370
#define LABEL_IO2                       371
#define IOBOX                           400
#define IDD_SINGLEENDED                 401
#define IDD_DIFFERENTIAL                402
#define IDD_CLK_INTERNAL                403
#define IDD_CLK_EXTERNAL                404
#define IDD_TRG_INTERNAL                405
#define IDD_TRG_EXTERNAL                406
#define IDD_RANGE                       407
#define IDD_BINARY                      408
#define IDD_2SCOMP                      409
#define IDD_SCANENABLE                  410
#define IDD_SCANFREQ                    411
#define IDD_TRG_DIGITAL                 412
#define CGLBOX                          500
#define IDD_CGLLIST                     501
#define IDD_CGLSCROLL                   502
#define IDD_CGLENTRY                    503
#define IDD_CGLSIZE                     504
#define IDD_CGLCHANNEL                  505
#define IDD_CGLGAIN                     506
#define IDD_RESET                       507
#define IDD_ADDENTRY                    509
#define IDD_CGLFILTER                   510
#define SVBOX                           600
#define IDD_SVINCHANNEL                 601
#define IDD_SVINGAIN                    602
#define IDD_SVGET                       603
#define IDD_SVVALUE                     604
#define IDD_SVOUTCHANNEL                605
#define IDD_SVOUTGAIN                   606
#define IDD_SVPUT                       607
#define CTBOX                           700
#define IDD_CTMODE                      701
#define IDD_CTFREQ                      702
#define IDD_FREQSTR                     703
#define IDD_CTSTART                     704
#define IDD_CTSTOP                      705
#define IDD_CTWIDTH                     706
#define IDD_WIDTHSTR                    707
#define IDD_EVENT                       708
#define IDD_EVENTSTR                    709
#define IDD_CTREAD                      710
#define IDD_START_EDGE                  711
#define IDD_STOP_EDGE                   712
#define IDD_START_EDGE_TITLE            713
#define IDD_STOP_EDGE_TITLE             714
#define IDD_MEASURE_FREQ                715
#define IDD_MEASURE_FREQ_STR            716
#define IDD_MEASURE_PERIOD              717
#define IDD_MEASURE_PERIOD_STR          718
#define DIGIOBOX                        800
#define IDC_ELEMENT_IN                  801
#define IDC_ELEMENT_OUT                 802
#define IDC_GET                         803
#define IDC_PUT                         804
#define IDC_RESOLUTION                  805
#define IDC_VALUE                       806
#define IDC_STATUS_OPEN_ANDOR           951
#define IDC_STATUS_OPEN_WHEEL           953
#define IDC_STATUS_OPEN_AOTF            954
#define IDC_STATUS_OPEN_GRAT            954
#define IDC_STATUS_OPEN_SCRIPT          955
#define IDC_STATUS_OPEN_LASERS          956
#define IDC_STATUS_OPEN_LED             957
#define IDC_STATUS_OPEN_STAGE           958
#define IDC_STATUS_OPEN_LASERS2         959
#define IDC_STATUS_OPEN_SCOPE           959
#define IDC_STAGE_545                   1046
#define IDC_STAGE_686                   1047
#define IDC_STAGE_CORRECT_XY            1048
#define IDC_STAGE_CENTER                1049
#define IDC_STAGE_POS                   1050
#define IDC_STAGE_DOWN                  1051
#define IDC_STAGE_UP                    1052
#define IDC_STAGE_FWD                   1053
#define IDC_STAGE_BACK                  1054
#define IDC_STAGE_RIGHT                 1055
#define IDC_STAGE_LEFT                  1056
#define IDC_STAGE_FWD2                  1057
#define IDC_STAGE_SSIZE_1               1058
#define IDC_STAGE_SSIZE_2               1059
#define IDC_STAGE_SSIZE_3               1060
#define IDC_STAGE_SSIZE_4               1061
#define IDC_STAGE_SSIZE_5               1062
#define IDC_STAGE_SCAN                  1065
#define IDC_STAGE_SCAN_Y                1066
#define IDC_STAGE_SCAN_X                1067
#define IDC_STAGE_SCAN_STEP_SIZE        1068
#define IDC_STAGE_STEP                  1069
#define IDC_STAGE_SAVE                  1070
#define IDC_STAGE_SAVE_GOTO             1071
#define IDC_STAGE_POS_SAVE              1072
#define IDC_LASERS                      1073
#define IDC_LASER_405                   1074
#define IDC_LASER_405ONOFF_BMP          1075
#define IDC_LASER_488                   1076
#define IDC_LASER_488ONOFF_BMP          1077
#define IDC_LASER_561                   1078
#define IDC_LASER_561ONOFF_BMP          1079
#define IDC_LASER_639                   1080
#define IDC_LASER_639ONOFF_BMP          1081
#define IDC_MGSHUTTERCTRL1              1082
#define IDC_MGSHUTTERCTRL2              1083
#define IDC_MGSHUTTERCTRL3              1084
#define IDC_MGSHUTTERCTRL4              1085
#define IDC_MG17LOGGERCTRL1             1086
#define IDC_MG17SYSTEMCTRL1             1087
#define IDC_CAMERA                      1600
#define IDC_CAS_DISP                    1601
#define IDC_TIME                        1602
#define IDC_CAS_STARTSTOP_PICTURE       1603
#define IDC_CAS_STARTSTOP_MOVIE         1604
#define IDC_CAS_MANUAL_GAIN             1605
#define IDC_CAS_DISPLAY_GAIN_MANUAL     1642
#define IDC_CAS_DISPLAY_GAIN_AUTOMATIC  1643
#define IDC_CAS_PICTURES_PER_FILE       1644
#define IDC_CAS_TEMP_TARGET             1646
#define IDC_CAS_TEMP_CURRENT            1647
#define IDC_CAS_DISPLAY_BIN_1           1648
#define IDC_CAS_DISPLAY_BIN_2           1649
#define IDC_CAS_DISPLAY_BIN_4           1650
#define IDC_CAS_DISPLAY_BIN_8           1651
#define IDC_CAS_GAIN_SINGLE             1652
#define IDC_CAS_EXPOSURE_TIME_SINGLE    1653
#define IDC_CAS_GAIN_MOVIE              1654
#define IDC_CAS_EXPOSURE_TIME_MOVIE     1655
#define IDC_CAS_START_MOVIE             1658
#define IDC_CAS_STOP_MOVIE              1660
#define IDC_CAS_STOP_MOVIE2             1661
#define IDC_CAS_PATHNAME                1662
#define IDC_CAS_SETPATH                 1663
#define IDC_CAS_PATH                    1664
#define IDC_CAS_SAVEONOFF_BMP           1665
#define IDC_CAS_SAVEONOFF               1666
#define IDC_CAS_FILEPREFIX              1667
#define IDC_CAS_VSSPEED_1               1700
#define IDC_CAS_VSSPEED_2               1701
#define IDC_CAS_VSSPEED_3               1702
#define IDC_CAS_VSSPEED_4               1703
#define IDC_CAS_VSSPEED_0               1704
#define IDC_CAS_HSSPEED_1               1705
#define IDC_CAS_HSSPEED_2               1706
#define IDC_CAS_HSSPEED_3               1707
#define IDC_CAS_HSSPEED_4               1708
#define IDC_CAS_HSSPEED_5               1709
#define IDC_CAS_HSSPEED_0               1710
#define IDC_CAS_FT                      1711
#define IDC_CAS_TTL                     1712
#define IDC_CAS_GL_0                    1713
#define IDC_CAS_GL_1                    1714
#define IDC_CAS_GL_2                    1715
#define IDC_CAM_SCOPE                   1716
#define IDC_CAS_PIC_0                   1717
#define IDC_CAS_PIC_1                   1718
#define IDC_CAS_PIC_2                   1719
#define IDC_CAS_MASK                    1720
#define IDC_CAS_SR                      1721
#define IDC_CAS_ALIGN                   1722
#define IDC_CAS_WIDE                    1723
#define IDC_CAS_RAW                     1724
#define IDC_CAS_LMM_0                   1725
#define IDC_CAS_LMM_1                   1726
#define IDC_CAS_LMM_2                   1727
#define IDC_CAS_LMM_3                   1728
#define IDC_CAS_FOCUSONOFF_BMP          1729
#define IDC_CAS_FOCUSONOFF              1730
#define IDC_STATIC_GAIN1                1731
#define IDC_STATIC_GAIN2                1732
#define IDC_STAGEm_CENTER               1849
#define IDC_STAGEm_POS                  1850
#define IDC_STAGEm_POS_SAVE             1851
#define IDC_STAGEm_FWD                  1853
#define IDC_STAGEm_BACK                 1854
#define IDC_STAGEm_RIGHT                1855
#define IDC_STAGEm_LEFT                 1856
#define IDC_STAGEm_SSIZE_1              1858
#define IDC_STAGEm_SSIZE_2              1859
#define IDC_STAGEm_SSIZE_3              1860
#define IDC_STAGEm_SSIZE_4              1861
#define IDC_STAGEm_SSIZE_5              1862
#define IDC_LAMBDA                      3042
#define IDC_SHUTTER_SLIDER              3043
#define IDC_SHUTTER_SLIDER_SETTING      3044
#define IDC_RADIO_SHUTR_OPEN            3045
#define IDC_SHUTTER_SLIDER_SETTING2     3045
#define IDC_RADIO_SHUTR_CLOSE           3046
#define IDC_SHUTTER_SLIDER_SETTING3     3046
#define IDC_RADIO_SHUTR_PARTIAL         3047
#define IDC_SHUTTER_SLIDER_SETTING4     3047
#define IDC_SHUTTER_SLIDER_SETTING5     3048
#define IDC_RADIO_FILTER_0              3055
#define IDC_RADIO_FILTER_1              3056
#define IDC_RADIO_FILTER_2              3057
#define IDC_RADIO_FILTER_3              3058
#define IDC_RADIO_FILTER_4              3059
#define IDC_RADIO_FILTER_5              3060
#define IDC_RADIO_FILTER_6              3061
#define IDC_RADIO_FILTER_7              3062
#define IDC_RADIO_FILTER_8              3063
#define IDC_RADIO_FILTER_9              3064
#define IDC_SCRIPT                      3100
#define IDC_LIST_SEQUENCE               3101
#define IDC_BUTTON_SEQ_LOAD             3102
#define IDC_BUTTON_SEQ_RUN              3103
#define IDC_BUTTON_SEQ_STOP             3104
#define IDC_SCR_RUNNING_BMP             3105
#define IDC_SCR_CYCLE                   3106
#define IDC_BUTTON_SEQ_LOAD2            3107
#define IDC_BUTTON_SEQ_LOAD3            3108
#define IDC_BUTTON_SEQ_LOAD4            3109
#define IDC_LED                         3200
#define IDC_LED_INTENSITY_SLIDER        3201
#define IDC_LED_INTENSITY               3202
#define IDC_LASER_INTENSITY_SLIDER      3202
#define IDC_LED_ADC                     3203
#define IDC_LED_ADC2                    3204
#define IDC_AOTF                        4001
#define IDC_AOTF_FREQ                   4002
#define IDC_AOTF_CH_1                   4003
#define IDC_AOTF_CH_2                   4004
#define IDC_AOTF_STARTSTOP              4005
#define IDC_AOTF_ONOFF_BMP              4006
#define IDC_SCOPE                       5001
#define TIMER_SCOPE                     5002
#define IDC_SCOPE_SSIZE_1               5003
#define IDC_SCOPE_SSIZE_2               5004
#define IDC_SCOPE_SSIZE_3               5005
#define IDC_SCOPE_SSIZE_4               5006
#define IDC_SCOPE_POS                   5007
#define IDC_SCOPE_DOWN                  5008
#define IDC_SCOPE_UP                    5009
#define IDC_SCOPE_ESC                   5010
#define IDC_SCOPE_RTN                   5011
#define IDC_SCOPE_OBJ_1                 5012
#define IDC_SCOPE_OBJ_2                 5013
#define IDC_SCOPE_OBJ_3                 5014
#define IDC_SCOPE_OBJ_4                 5015
#define IDC_SCOPE_OBJ_5                 5016
#define IDC_SCOPE_OBJ_6                 5017
#define IDC_SCOPE_PATH                  5018
#define IDC_SCOPE_CLEAN_TO              5019
#define IDC_SCOPE_CLEAN_FROM            5020
#define IDC_SCOPE_INTENSITY_SLIDER      5021
#define IDC_SCOPE_INTENSITY_SLIDER_SETTING 5022
#define IDC_SCOPE_FW_1                  5023
#define IDC_SCOPE_FW_2                  5024
#define IDC_SCOPE_FW_3                  5025
#define IDC_SCOPE_FW_4                  5026
#define IDC_SCOPE_FW_5                  5027
#define IDC_SCOPE_FW_6                  5028
#define IDC_SCOPE_BFW_1                 5029
#define IDC_SCOPE_BFW_2                 5030
#define IDC_SCOPE_BFW_3                 5031
#define IDC_SCOPE_BFW_4                 5032
#define IDC_SCOPE_BFW_5                 5033
#define IDC_SCOPE_BFW_6                 5034
#define IDC_STATUS_OPEN_PIEZO           6108
#define IDC_PIEZO                       6109
#define IDC_PIEZO_DOWN                  6110
#define IDC_PIEZO_CENTER                6111
#define IDC_PIEZO_UP                    6112
#define IDC_PIEZO_SAVE                  6113
#define IDC_PIEZO_SAVE_GOTO             6114
#define IDC_PIEZO_SSIZE_1               6115
#define IDC_PIEZO_SSIZE_2               6116
#define IDC_PIEZO_SSIZE_3               6117
#define IDC_PIEZO_SSIZE_4               6118
#define IDC_PIEZO_POS                   6119
#define IDC_PIEZO_FOCUS                 6120
#define IDC_PIEZO_FOCUS_SCORE           6121
#define IDC_PIEZO_FOCUS_RUNNING_BMP     6122
#define IDC_PIEZO_CENTERXY              6123
#define IDC_PIEZO_SSIZE_5               6124
#define IDC_STATUS_OPEN_POL             7100
#define IDC_POL_CCW                     7101
#define IDC_POL_CW                      7102
#define IDC_POL_ZERO                    7103
#define IDC_POL_REP_POS                 7104
#define IDC_POL_REP_SAVE                7105
#define IDC_POL_REP_STEP                7106
#define IDC_MGMOTORCTRL1                7107
#define IDC_STAGE_POL                   7108
#define IDC_POL_ZERO2                   7108
#define IDC_POL_SAVE                    7109
#define IDC_GRAT                        7109
#define IDC_POL_SAVE_GOTO               7110
#define IDC_STAGE_POL_LC                7110
#define IDC_POL_SCAN                    7111
#define IDD_LASER                       7111
#define IDC_POL_SCAN_STEP_SIZE          7112
#define IDC_POL_SCAN_STEP_NUMBER        7113
#define IDC_POL_SCAN_SET_START          7114
#define IDC_POL_SCAN_STEP_SIZE_Z        7115
#define IDC_POL_SCAN_STEP_NUMBER_Z      7116
#define IDC_POL_MIC                     7117
#define IDC_POL_CW2                     7117
#define IDC_POL_ROT                     7118
#define IDC_POL_CCW2                    7119
#define IDC_POL_SAVE_GOTO2              7120
#define IDC_POL_SAVE2                   7121
#define IDC_MGMOTORCTRL2                7122
#define IDC_POL_SCAN_SET_START2         7123
#define IDC_POL_ROT2                    7124
#define IDC_POL_ROT3                    7125
#define IDC_POL_ROTONOFF_BMP            8002
#define IDC_LAMBDA_TEXT_7               8004
#define IDC_SNAP_BUTTON                 8005
#define IDC_LAMBDA_TEXT_8               8006
#define IDC_SNAP_POWER                  8007
#define IDC_CHECK_IMAGEJ                8008
#define IDC_RADIO1                      8013
#define IDC_GENERAL_FOCUS               8013
#define IDC_BUTTON3                     8014
#define IDC_BEAD_FOCUS                  8014
#define IDC_BUTTON1                     8016
#define LED_INTENSITY_VIEW              8017
#define LED_Submit_Intensity            8018
#define IDC_LASER_SLIDER                8019
#define LASER_INTENSITY_VIEW            8019
#define IDC_LASER_INPUT                 8020
#define LED_Submit_Intensity2           8020
#define IDC_LASERS_SLIDER               8021
#define LED_Submit_Intensity3           8021
#define LED_Submit_Intensity4           8022
#define IDC_STATUS_OPEN_FOCUS           8023
#define IDC_NOFOCUS                     8029
#define IDC_CHECK1                      8030
#define IDC_FOCUSTYPE                   8030
#define IDC_DOUT1                       8030
#define IDC_DOUT2                       8031
#define IDC_DOUT3                       8032
#define IDC_FOCUS_EDIT                  8033
#define IDC_DOUT4                       8033
#define IDC_FOCUS_TEXT                  8034
#define IDC_DOUT5                       8034
#define IDC_DOUT6                       8035
#define IDC_DOUT7                       8036
#define IDC_CHECK8                      8037
#define IDC_DOUT8                       8037
#define IDC_ReturnFilterControl         8037
#define IDC_BUTTON_GOTOXY               8038
#define IDC_GOTOX                       8039
#define IDC_EDIT2                       8040
#define IDC_GOTOY                       8040
#define IDC_GRAT_FWD                    8110
#define IDC_GRAT_CENTER                 8111
#define IDC_GRAT_BACK                   8112
#define IDC_GRAT_SAVE                   8113
#define IDC_GRAT_SAVE_GOTO              8114
#define IDC_GRAT_SSIZE_1                8115
#define IDC_GRAT_SSIZE_2                8116
#define IDC_GRAT_SSIZE_3                8117
#define IDC_GRAT_SSIZE_4                8118
#define IDC_GRAT_SSIZE_5                8119
#define IDC_GRAT_POS                    8120

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        116
#define _APS_NEXT_COMMAND_VALUE         40016
#define _APS_NEXT_CONTROL_VALUE         8041
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
